### ISSUE TITLE
`syms FF(w)` fails

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#290]

**Comment by latot** [comment]
from python:
```
z = sympy.S("FF(w)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/core/sympify.py", line 322, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/usr/lib64/python2.7/site-packages/sympy/parsing/sympy_parser.py", line 892, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/usr/lib64/python2.7/site-packages/sympy/parsing/sympy_parser.py", line 805, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/polys/domains/pythonfinitefield.py", line 17, in __init__
    return super(PythonFiniteField, self).__init__(mod, PythonIntegerRing(), symmetric)
  File "/usr/lib64/python2.7/site-packages/sympy/polys/domains/finitefield.py", line 29, in __init__
    if mod <= 0:
  File "/usr/lib64/python2.7/site-packages/sympy/core/relational.py", line 196, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```

**Comment by cbm755** [comment]
Thanks.  Might be related to https://github.com/sympy/sympy/issues/9057.

**Comment by latot** [comment]
i think this isn't a bug, actually sympy claims if you try to make a sym of a function, its the same with matrix:
```
>>> S("Matrix(w)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/core/sympify.py", line 322, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/usr/lib64/python2.7/site-packages/sympy/parsing/sympy_parser.py", line 894, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/usr/lib64/python2.7/site-packages/sympy/parsing/sympy_parser.py", line 807, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/matrices/dense.py", line 611, in __new__
    return cls._new(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sympy/matrices/dense.py", line 603, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sympy/matrices/matrices.py", line 227, in _handle_creation_inputs
    raise TypeError("Data type not understood")
TypeError: Data type not understood
```
maybe the right focus to this is check if exist the input as a functions and send an error in that case.

**Comment by latot** [comment]
Hi, well working a little in this, i concluded its necessary takes some decisions, actually the sym function have the feature to can call directly sympy functions, but that enables this problem, you can't make a symfun with the name of some function, but if we disable that calls we will lost that feature, this problem only appears when we make some symfun with a name of a python function, if you try make a sym with "Eq" will works but with "Eq(t)" will fails, and this affects directly when we creates symfuns.

Personally, i think would be more safe disable the python env functions in the octave env(only symfuns), you can't make that sym in python -> you can't make that sym in octave.

About things like MatrixSymbol, i think we can do some new function or improve that things in the sym function instead calls like this: https://github.com/cbm755/octsympy/issues/143

Well, actually i have the code to disable this, if you are agree check this plis: https://github.com/cbm755/octsympy/pull/558

Cya.

**Comment by cbm755** [comment]
Seems a bit premature to call this closed.  `sym('FF')` is fixed but the symfun issue is still open.  So if `sym('Eq(t)')` as mentioned in #559.
