### ISSUE TITLE
[windows] test failures

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#454]
Part of the output from the 2.4.0 tests on Windows 10, using the bundle and a patched Octave 4.0.2:

````
Traceback (most recent call last):
  File "py.py", line 896, in <module>
  File "<string>", line 1, in <module>
IOError: [Errno 22] invalid mode ('r') or filename: 'C:\\Users\x07non\test_oct\\octave-4.0.2-p\\
share\\octave\\packages\\symbolic-2.4.0\\private\\python_header.py'
status =  127
out =
ind = [](0x0)
Traceback (most recent call last):
  File "py.py", line 896, in <module>
  File "<string>", line 1, in <module>
IOError: [Errno 22] invalid mode ('r') or filename: 'C:\\Users\x07non\test_oct\\octave-4.0.2-p\\
share\\octave\\packages\\symbolic-2.4.0\\private\\python_header.py'
status =  127
out =
ind = [](0x0)
Traceback (most recent call last):
  File "py.py", line 896, in <module>
  File "<string>", line 1, in <module>
IOError: [Errno 22] invalid mode ('r') or filename: 'C:\\Users\x07non\test_oct\\octave-4.0.2-p\\
share\\octave\\packages\\symbolic-2.4.0\\private\\python_header.py'
status =  127
out =
ind = [](0x0)
````
This is from `test sympref`, probably ipc `system` or `sysoneline`...

Q: my username is `anon`: why did it get changed to `x07non`?  Is that the problem?

Q: or `invalid mode ('r')` thing the problem?

**Comment by cbm755** [comment]
I cannot reproduce with a standard 4.0.0 install.  Perhaps its specific to the patched built I was using.  Anyway, I'll re-open if I see it again
