### ISSUE TITLE
Rewrite Solve for SMT compat + Multiples Bugs

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#581]
Hi, well, it feels this will be something big, this function its too far from SMT, and have a lot of wrong behaviors, principally Sympy problems, i'll need report a lot of it, but for the moment we need some fix, so i'll try update this with the problems i can found:
- [ ] If we send some ineq we can't pass the returns in a list

```
>>> solve((y>1), [x])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/solvers.py", line 830, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/inequalities.py", line 664, in reduce_inequalities
    symbols = (set(symbols) or gens) & gens
TypeError: unhashable type: 'list'
```

sol: `*[x]`
- [ ] We can't request a value with multiples depends in eqs only if don't exist any ineq:

```
>>> solve([Eq(x+y,1), Eq(x-y,1)], x)
[]
>>> solve([Eq(x,1), Eq(x+y,1)], x)
[]
This works (when only depend of one eq):
>>> solve([Eq(y,1), Eq(x+y,1)], x)
{x: -y + 1}
```

sol: request all symbols and match which you need
- [ ] similar of above, if we request a value but with only depend of one eqs the system don't is solved:

```
>>> solve([Eq(y,1), Eq(x+y,1)], x)
{x: -y + 1}
```

sol: same as above
- [ ] If the expression don't exist in the system don't is returned (in that case we should pass a set of (-oo, oo):

```
>>> solve([Eq(x+y,1), Eq(x-y,1)], [x, y, z])
{x: 1, y: 0}
```

sol: search symbols don't exist in sol and set the set(-oo, oo).
- [ ] if we request a value and it depends of multiples eqs without uniq solution we only get one:

```
>>> solve([Eq(x+y+z,1), Eq(x-y,1)], z)
{z: -x - y + 1}
```

sol: permute requested var in all eqs and join the solutions.
- [ ] requesting values + mutiples vars + eqs + ineq returns non sense:

```
>>> solve([Eq(x+y,0), Eq(x-y, 0), x>0], x)
And(0 < x, Eq(x, -y), Eq(x, y), x < oo)
>>> solve([Eq(x+y,0), Eq(x-y, 0), x>0], y)
And(0 < x, Eq(y, -x), Eq(y, x), x < oo)
```

no sol, send a error message 'not supported'
very probable sol, request all vars and match with which you need.
- [ ] if we request more than two vars with infinite solutions we only get the first:

```
>>> solve([Eq(20*x,20*y)], x, y)
{x: y}
```

sol: in this case use a recursion of all vars in the eqs to get the solutions.
- [ ] true is recognized as ineq:

```
>>> a=solve([true, Eq(x, y)], x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/solvers.py", line 830, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/inequalities.py", line 694, in reduce_inequalities
    rv = _reduce_inequalities(inequalities, symbols)
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/inequalities.py", line 615, in _reduce_inequalities
    symbol of interest'''))
NotImplementedError: 
inequality has more than one symbol of interest
```

sol: search true in eqs ans remove it (only true).
- [ ] We only will get the same number of solutions of eq given:

```
>>> solve([Eq(x+y+z,1), Eq(y-z,1)], x, y, z)
{x: -2*z, y: z + 1}
>>> solve([Eq(x+y+z,1)], x, y, z)
{x: -y - z + 1}
```

sol: permute requested vars to get all solutions and join multiples sols.
- [ ] If you ask a non symbol and some var don't have a numerical coeff we don't get a solution:

```
>>> solve([Eq(x, y*2)], x*2)
[]
This works.
>>> solve([Eq(x*2, y*2)], x*2)
{2*x: 2*y}
```

sol: ask normal symbols, then eval it.
- [ ] format don't is consistent with ineq + eqs:

```
>>> solve([Eq(x**2-1,0), x>0])
Eq(x, 1)
>>> solve([Eq(x**2-1,0), x>0], set=True)
Eq(x, 1)
>>> solve([Eq(x**2-1,0), x>0], dict=True)
Eq(x, 1)
```
- [ ] if in the solution exist a imaginary the solutions will be skipped and we will get False:

```
>>> solve([Eq(-x**3+x-1,0), x<0])
False
the solution should be:
-(3*sqrt(69)/2 + 27/2)**(1/3)/3 - 1/(3*sqrt(69)/2 + 27/2)**(1/3)
```

Sadly for the moment we need a solution for all this and in future versions of Sympy we can use better code.

Thx. Cya.

**Comment by latot** [comment]
a very safe way to solve this, but it will requieres a hard works its use solveset

**Comment by latot** [comment]
Hi, i think we should not fix this from here, i actually already open bugs for all this in sympy, so just lets wait it.
