### ISSUE TITLE
Symfun don't replace correctly in matrix

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#633]
Hi all, well again other issue:

```
f(x) = (symfun) x + 1
octave:60> g
g = (sym) [1  2]  (1×2 matrix)
octave:61> f([1;2])
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 54, in octoutput
  File "<stdin>", line 34, in octoutput
  File "/usr/lib64/python2.7/site-packages/sympy/core/basic.py", line 399, in __str__
    return sstr(self, order=None)
  File "/usr/lib64/python2.7/site-packages/sympy/printing/str.py", line 761, in sstr
    s = p.doprint(expr)
  File "/usr/lib64/python2.7/site-packages/sympy/printing/printer.py", line 233, in doprint
    return self._str(self._print(expr))
  File "/usr/lib64/python2.7/site-packages/sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sympy/printing/str.py", line 51, in _print_Add
    terms = self._as_ordered_terms(expr, order=order)
  File "/usr/lib64/python2.7/site-packages/sympy/printing/printer.py", line 271, in _as_ordered_terms
    return expr.as_ordered_terms(order=order)
  File "/usr/lib64/python2.7/site-packages/sympy/core/expr.py", line 902, in as_ordered_terms
    terms, gens = self.as_terms()
  File "/usr/lib64/python2.7/site-packages/sympy/core/expr.py", line 932, in as_terms
    coeff, _term = term.as_coeff_Mul()
  File "/usr/lib64/python2.7/site-packages/sympy/matrices/matrices.py", line 121, in __getattr__
    "%s has no attribute %s." % (self.__class__.__name__, attr))
AttributeError: ImmutableMatrix has no attribute as_coeff_Mul.
error: Python exception: AttributeError: ImmutableMatrix has no attribute as_coeff_Mul.
    occurred while copying vars from Python
error: called from
    python_cmd at line 176 column 5
    subs at line 160 column 5
    subsref at line 46 column 11
```

The expected behavior is every element of the matrix should apply the function, at least this is what octave does.

One question should be, what should do if f and g are matrix?
i think to match a little this for now it can apply every value of g in f, creating a new matrix.
Now, the matrix should be a matrix of matrix? or join all?

Thx. Cya.

**Comment by cbm755** [comment]
This looks like Issue #10.

 There was a special case made for `sym/subs`, perhaps something similar should be done for evaluating at `symfun` as well?
