### ISSUE TITLE
`test @sym/mpower` fails with SymPy 1.0.1.dev

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#787]
The test for a scalar raised to a matrix exponent fails with a different than expected error with SymPy 1.0.1.dev.

In Python, the new behavior is

    >>> x = S('x')
    >>> A = Matrix([[1, 2], [3, 4]])
    >>> x**A
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/home/mike/src/sympy/sympy/core/decorators.py", line 78, in __sympifyit_wrapper
        return func(a, b)
      File "/home/mike/src/sympy/sympy/core/decorators.py", line 119, in binary_op_wrapper
        return func(self, other)
      File "/home/mike/src/sympy/sympy/core/expr.py", line 150, in __pow__
        return Pow(self, other)
      File "/home/mike/src/sympy/sympy/core/cache.py", line 93, in wrapper
        retval = cfunc(*args, **kwargs)
      File "/home/mike/src/sympy/sympy/core/compatibility.py", line 792, in wrapper
        return user_function(*args, **kwds)
      File "/home/mike/src/sympy/sympy/core/power.py", line 217, in __new__
        c, ex = factor_terms(e, sign=False).as_coeff_Mul()
      File "/home/mike/src/sympy/sympy/matrices/matrices.py", line 2217, in __getattr__
        "%s has no attribute %s." % (self.__class__.__name__, attr))
    AttributeError: ImmutableDenseMatrix has no attribute as_coeff_Mul.

In previous versions we were expecting the `NotImplementedError`, now raises an `AttributeError`. If this is the correct new behavior, could fix by simply updating the error regex to match both possible errors.

**Comment by latot** [comment]
Hi, i think is a bad message, because i can think 2 posibilites, one in upstream try implement that but don't is finished, second, some weird/bad change, i would prefer ask this there.

**Comment by mtmiller** [comment]
Maybe so. The upstream commit that introduced this change is [9c60ca463](https://github.com/sympy/sympy/commit/9c60ca463). I can't tell what the intended behavior is now, if this is a case that should produce a better error or what.

**Comment by mtmiller** [comment]
This has now been fixed upstream. Our test now fails because this _is_ implemented in SymPy 1.0.1.dev:

    >> syms x
    >> A = [1 2; 3 4];
    >> B = x^A
    B = (sym)
    
       ⎡1  2⎤
       ⎢    ⎥
       ⎣3  4⎦
      x
