### ISSUE TITLE
sympref tests fail on pythonic w/ python3

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#972]
CI runs using python3 and pythonic are failing:
```
  /octsympy/inst/python_cmd.m .................................... PASS   46/46  
  /octsympy/inst/sympref.m .......................................Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sympy
```

Probably `test sympref` resets something to default and tries `python` instead of `python3`, then b/c some test has failed it never resets to the saved previous state.  Or something like that.

**Comment by mtmiller** [comment]
Unable to reproduce locally. I think you're right, and I think ab4459f1b3c6 may fix this.
